letsencrypt:
  build: .
  container_name: letsencrypt
  expose:
    - 80
  volumes:
    - /certs:/certs
  restart: always
  environment:
    - DOMAINS=domain1.com domain2.com
    - EMAIL=webmaster@domain1.com
    - DH_PARAMETERS=false
    - MERGE_KEY_WITH_CERTIFICATE=false
